import { useState } from 'react'
import { UserSettings } from '../types/attachment'
import { MoodKey, moodData } from '../data/moods'

interface TherapyExportProps {
  settings: UserSettings
  myMood?: MoodKey
  partnerMood?: MoodKey
}

export default function TherapyExport({ settings, myMood, partnerMood }: TherapyExportProps) {
  const [isOpen, setIsOpen] = useState(false)

  const generateTherapyReport = () => {
    const timestamp = new Date().toLocaleString()

    const report = `ATTACHMENT WORKBOOK - THERAPY SESSION NOTES
Generated: ${timestamp}

=== SYSTEM CONFIGURATION ===
Node A: ${settings.myName}
- Primary Attachment Style: ${settings.myAttachment}
${settings.myAttachmentSecondary ? `- Secondary Style: ${settings.myAttachmentSecondary}` : ''}
- Current Status: ${myMood ? moodData[myMood].label : 'Not set'}

Node B: ${settings.partnerName}
- Primary Attachment Style: ${settings.partnerAttachment}
${settings.partnerAttachmentSecondary ? `- Secondary Style: ${settings.partnerAttachmentSecondary}` : ''}
- Current Status: ${partnerMood ? moodData[partnerMood].label : 'Not set'}

=== CURRENT DYNAMICS ===
${myMood ? `Node A Mood: ${moodData[myMood].description}` : ''}
${partnerMood ? `Node B Mood: ${moodData[partnerMood].description}` : ''}

=== PATTERN NOTES ===
(Space for therapist/client notes about recurring patterns)

- Communication Style:

- Conflict Resolution:

- Connection Needs:

- Autonomy Needs:

=== ACTION ITEMS ===
(Goals and homework for next session)

1.
2.
3.

=== NEXT SESSION ===
Date: _______________
Focus Areas:

---
Generated by Attachment Workbook - Systems Engineering Approach to Relationships
`

    // Create download
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `therapy-notes-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white px-6 py-3 rounded-xl font-semibold transition"
      >
        📋 Therapy Export
      </button>

      {isOpen && (
        <div className="mt-4 bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold">Export Session Notes</h3>
            <button
              onClick={() => setIsOpen(false)}
              className="text-slate-400 hover:text-white"
            >
              ✕
            </button>
          </div>

          <p className="text-sm text-slate-300 mb-4">
            Generate a therapy-friendly summary of your current attachment configuration and system status.
            This can be shared with your therapist or used for personal reflection.
          </p>

          <div className="space-y-3">
            <div className="bg-slate-900/50 rounded-lg p-3 text-xs">
              <div className="font-semibold text-slate-300 mb-2">Export includes:</div>
              <ul className="text-slate-400 space-y-1 list-disc list-inside">
                <li>Attachment style configuration (primary + secondary)</li>
                <li>Current mood states for both partners</li>
                <li>Space for pattern notes and observations</li>
                <li>Action items and session planning</li>
              </ul>
            </div>

            <button
              onClick={generateTherapyReport}
              className="w-full bg-white/10 hover:bg-white/20 text-white py-2 rounded-lg font-semibold transition"
            >
              Download Report (.txt)
            </button>
          </div>

          <div className="mt-4 text-xs text-slate-500">
            The exported file is a text document you can edit, print, or email to your therapist.
            All data is generated locally and never sent to any server.
          </div>
        </div>
      )}
    </div>
  )
}
